-- V3__Create_Cast.sql

-- This migration defines implicit casts from VARCHAR to all custom enums to allow easy inserts and comparisons.

CREATE CAST (VARCHAR AS verification_status) WITH INOUT AS IMPLICIT;
CREATE CAST (VARCHAR AS verification_method) WITH INOUT AS IMPLICIT;
CREATE CAST (VARCHAR AS risk_level) WITH INOUT AS IMPLICIT;
CREATE CAST (VARCHAR AS document_type) WITH INOUT AS IMPLICIT;
CREATE CAST (VARCHAR AS verification_purpose) WITH INOUT AS IMPLICIT;
CREATE CAST (VARCHAR AS corporate_document_type) WITH INOUT AS IMPLICIT;
CREATE CAST (VARCHAR AS power_type) WITH INOUT AS IMPLICIT;
CREATE CAST (VARCHAR AS screening_type) WITH INOUT AS IMPLICIT;
CREATE CAST (VARCHAR AS screening_result) WITH INOUT AS IMPLICIT;
CREATE CAST (VARCHAR AS list_type) WITH INOUT AS IMPLICIT;
CREATE CAST (VARCHAR AS resolution_status) WITH INOUT AS IMPLICIT;
CREATE CAST (VARCHAR AS assessment_type) WITH INOUT AS IMPLICIT;
CREATE CAST (VARCHAR AS risk_category) WITH INOUT AS IMPLICIT;
CREATE CAST (VARCHAR AS ownership_type) WITH INOUT AS IMPLICIT;
CREATE CAST (VARCHAR AS relationship_type) WITH INOUT AS IMPLICIT;
CREATE CAST (VARCHAR AS source_type) WITH INOUT AS IMPLICIT;
CREATE CAST (VARCHAR AS case_type) WITH INOUT AS IMPLICIT;
CREATE CAST (VARCHAR AS case_status) WITH INOUT AS IMPLICIT;
CREATE CAST (VARCHAR AS case_priority) WITH INOUT AS IMPLICIT;
CREATE CAST (VARCHAR AS action_type) WITH INOUT AS IMPLICIT;
CREATE CAST (VARCHAR AS action_status) WITH INOUT AS IMPLICIT;
CREATE CAST (VARCHAR AS report_type) WITH INOUT AS IMPLICIT;
CREATE CAST (VARCHAR AS report_status) WITH INOUT AS IMPLICIT;
CREATE CAST (VARCHAR AS edd_reason) WITH INOUT AS IMPLICIT;
CREATE CAST (VARCHAR AS edd_status) WITH INOUT AS IMPLICIT;
CREATE CAST (VARCHAR AS verification_document_type) WITH INOUT AS IMPLICIT;
